apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: rescuehub
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: rescuehub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
