apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
  namespace: rescuehub
  labels:
    app.kubernetes.io/name: django-media
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: rescuehub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
