apiVersion: v1
kind: Service
metadata:
  name: rescuehub-web
  namespace: rescuehub
  labels:
    app.kubernetes.io/name: rescuehub-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: rescuehub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rescuehub-web
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8000
      targetPort: http
