# Generated by Django 5.1.7 on 2026-04-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlog",
            name="adoption_request",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdoptionRequest",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
