# Generated by Django 5.1.7 on 2026-06-01 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_auditlog_adoption_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documentos/', verbose_name='Documentação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_adocao', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_adocao', to='core.animal')),
            ],
            options={
                'verbose_name': 'Pedido de Adoção',
                'verbose_name_plural': 'Pedidos de Adoção',
                'ordering': ['-created_at'],
            },
        ),
    ]
